CREATE TABLE `career_guidance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentUserId` int NOT NULL,
	`professorUserId` int,
	`careerTrack` enum('brand_design','sns_marketing','video_editing','character_goods','ai_generation','freelancer','undecided') NOT NULL DEFAULT 'undecided',
	`recommendedCompanies` json,
	`checklist` json,
	`guidanceNote` text,
	`aiRecommendReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `career_guidance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `company_pipeline` (
	`id` int AUTO_INCREMENT NOT NULL,
	`partnerCompanyId` int,
	`companyName` varchar(200) NOT NULL,
	`contactName` varchar(100),
	`contactPhone` varchar(20),
	`contactEmail` varchar(320),
	`industry` varchar(100),
	`stage` enum('discovery','contact','negotiation','mou_signed') NOT NULL DEFAULT 'discovery',
	`availablePositions` json,
	`expectedHeadcount` int DEFAULT 0,
	`note` text,
	`nextAction` text,
	`nextActionDate` timestamp,
	`managedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `company_pipeline_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employment_success_banner` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentUserId` int NOT NULL,
	`studentName` varchar(100) NOT NULL,
	`useInitial` boolean NOT NULL DEFAULT true,
	`companyName` varchar(200) NOT NULL,
	`jobTitle` varchar(200) NOT NULL,
	`message` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`isAutoGenerated` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `employment_success_banner_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employment_tracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentUserId` int NOT NULL,
	`graduationDate` timestamp,
	`employedAt` timestamp,
	`companyName` varchar(200),
	`jobTitle` varchar(200),
	`employmentType` enum('정규직','계약직','프리랜서','인턴'),
	`salary` int,
	`checkD30` boolean DEFAULT false,
	`checkD60` boolean DEFAULT false,
	`checkD90` boolean DEFAULT false,
	`checkD30Note` text,
	`checkD60Note` text,
	`checkD90Note` text,
	`source` enum('platform','professor_match','self','other') DEFAULT 'self',
	`jobApplicationId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employment_tracking_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `freelancer_activity` (
	`id` int AUTO_INCREMENT NOT NULL,
	`studentUserId` int NOT NULL,
	`platform` enum('kmong','kakao','soomgo','other') NOT NULL,
	`profileUrl` text,
	`monthlyRevenue` int DEFAULT 0,
	`projectCount` int DEFAULT 0,
	`rating` float,
	`isActive` boolean NOT NULL DEFAULT true,
	`note` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `freelancer_activity_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `portfolio_views` (
	`id` int AUTO_INCREMENT NOT NULL,
	`portfolioId` int NOT NULL,
	`viewerUserId` int,
	`viewerIp` varchar(45),
	`viewerRole` varchar(50),
	`companyName` varchar(200),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `portfolio_views_id` PRIMARY KEY(`id`)
);
